language: ruby
rvm:
- 2.2

before_script:
 - gem install bundler # or do this locally and commit
 - bundle install
 # - gem install jekyll
 # - gem install jekyll-feed
 # - gem install jekyll-paginate
 # - gem install jekyll-minifier

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:

 - git clone https://${GHTK}@github.com/flinhong/flinhong.github.io.git public
 - bundle exec jekyll build -d public
 
 - cd public
 - git config --global user.name "Frank Lin (林宏)"
 - git config --global user.email "flinhong@hotmail.com"
 - git config --global push.default simple
 - git add .
 - git commit -m "update site through travis ci"
 - git push --set-upstream "https://${GHTK}@github.com/flinhong/flinhong.github.io.git"

 
# branch whitelist, only for GitHub Pages
branches:
  only:
  - jekyll     # test the deploy branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

